### ISSUE TITLE
WGCNA results

### ISSUE THREAD

**Issue by hernandezvargash** [skoplev/starnet#3]
Thank you for creating this repository,
I'd like to compare your WGCNA network with one obtained form an independent dataset.
Are the network results (adjacency, modules, etc.) published here or somewhere else?
Thanks!

**Comment by skoplev** [comment]
Hi Hernandez,

Thank you for the interest in our study. There is not much data deposited in the Github repository directly. We have put data such as modules in the Source Data section of: https://www.nature.com/articles/s44161-021-00009-1
organized by figures. For instance, there is a table of modules for the associated fig 2 data in "d) modules" page. The full (but block-wise) adjacency matrices, however, are on the Mount Sinai cluster -- as far as I recall. Would recommend reaching out to Johan for this or let me know and I might have a copy somewhere as well. Alternatively, these could be recomputed from the deposited normalized expression counts.

Hope that helps!

**Comment by hernandezvargash** [comment]
Thanks!
